TIME_UTC problem workaround (boost 1.49, C++11)
Definition of TIME_UTC in boost/thread/xtime.hpp conflicts with
glibc definition of TIME_UTC (C++11). Both of them define
TIME_UTC = 1. This problem was fixed in boost 1.50, but Wt
declares needed boost version >= 1.41, so it should compile
against versions < 1.50 with modern g++ with C++11 support.

Example of error message:

In file included from /usr/include/boost/thread/pthread/mutex.hpp:14:0,
                 from /usr/include/boost/thread/mutex.hpp:16,
                 from /usr/include/boost/spirit/home/classic/core/non_terminal/impl/object_with_id.ipp:17,
                 from /usr/include/boost/spirit/home/classic/core/non_terminal/impl/grammar.ipp:15,
                 from /usr/include/boost/spirit/home/classic/core/non_terminal/grammar.hpp:21,
                 from /usr/include/boost/spirit/home/classic/core.hpp:42,
                 from /usr/include/boost/spirit/include/classic_core.hpp:11,
                 from /wt/src/http/StaticReply.C:8:
/usr/include/boost/thread/xtime.hpp:23:5: error: expected identifier before numeric constant
/usr/include/boost/thread/xtime.hpp:23:5: error: expected ‘}’ before numeric constant

gcc version 4.7.2

See https://bbs.archlinux.org/viewtopic.php?id=144593