WT-9414: fix linking issue on Fedora 35
I got this error:

error: '/usr/lib64/libdl.so', needed by
'wt/src/Wt/Dbo/backend/libwtdbosqlite3d.so.4.6.0', missing and no known
rule to make it

Simply using ${CMAKE_DL_LIBS} fixes it.