WCartesian3DChart: rename variables near and far
"near" and "far" are defined in minwindef.h (mingw-w64):

    #define far
    #define near

Error message:

    wt-3.3.4/src/Wt/Chart/WCartesian3DChart.C:330:16: error:
    expected primary-expression before '(' token
        WVector4 far(
                    ^